name: CI Pipeline for my project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh 
          echo '$HOME/.local/bin' >> $GITHUB_PATH

      - name: Debug Cache Key
        run: echo "Cache Key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}"
        
      - name: Cache UV dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.cargo/bin/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv pip install --generate-lock-file

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build application
        run: |
          # Add specific build commands here
          echo "Build step executed successfully"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          uv run pytest -vvv -s tests/*.py
