name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      
      - name: Install Python 3.12
        uses: actions/setup-python@v5  
        with:
          python-version: "3.12"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Cache uv dependencies
        uses: actions/cache@v4  
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check uv version
        run: uv --version
      
      - name: Set up Python and install dependencies
        run: |
          uv sync --all-extras --dev
      
      - name: Adding other necessary files
        run: |
          cp -r static templates 

      - name: Build application
        run: uv build
      
      - name: Upload build artifacts  
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 5


  lint:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff
        run: uvx ruff check .
        

  test:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Download build artifacts  
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/
      
      - name: Install test dependencies and run tests
        run: |
          uv run pytest -vvv -s tests/*.py --cov=./ --cov-report=xml
      
      - name: Upload coverage reports  
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true