name: CI Pipeline for my project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
  
      - name: Verify uv Installation
        run: |
          echo "Checking uv version:"
          uv --version
      

      - name: Debug Cache Key
        run: |
          echo "Cache Key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}"
        
        
      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use cached environment
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Verify uv Availability
        run: uv --version

      - name: Build application
        run: uv build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Restore UV binary
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          uv run pytest -vvv -s tests/*.py
